[mypy]
python_version = 3.13
ignore_missing_imports = True
# Suppress SQLAlchemy related issues and some dynamic attribute access in tests
disable_error_code = valid-type, attr-defined, misc, index, import-untyped
exclude = .venv/
